---
title: "Extracurricular Activities"
---


## Head of Conference Committee, Aurora Conference on Generative AI (2025)
_Department of Computer Science, USJ_

- Led the planning and execution of a high-profile conference on Generative AI.
- Liaised with speakers and industry experts, ensuring successful event management and collaboration.
- Managed academic–industry partnerships, speaker outreach, and seamless team coordination.
- [Certificate](https://drive.google.com/file/d/1sWkL5LcSyLoSoibmZCKnUtXTbv107jQp/view?usp=drivesdk) | [LinkedIn Post](https://www.linkedin.com/posts/sathmi-wijeratna-3a81b32a0_auroraconference-generativeai-digitalentrepreneurship-activity-7239961943220871169-qtCX?utm_source=share&utm_medium=member_ios&rcm=ACoAAEik3XAB8Tdu2sHOShs5njSOLrumK4NYK2M) <!-- Add links if available -->

---

## Secretary – Statistics Society (2023–Present)
_University of Sri Jayewardenepura_

- Managed official communication, documentation, and event organization for the society.
- Coordinated schedules, subcommittees, and major academic competitions (e.g., "DataXplore").
- Contributed to outreach, report writing, and faculty/industry coordination.
- [Society Website](https://science.sjp.ac.lk/statsoc/)  <!-- Add links if available -->
---
